---
title: "Robert Maidstone"
---

<!-- I am a Research Associate at [OCDEM](https://www.rdm.ox.ac.uk/about/our-divisions/oxford-centre-for-diabetes-endocrinology-and-metabolism){target="_blank"} (University of Oxford), part of [Prof. David Ray's](https://www.rdm.ox.ac.uk/people/david-ray){target="_blank"} lab. -->

<!-- My recent work uses computational techniques to explore the relationships between the circadian clock and disease. In particular looking at the effect of disruption to the circadian system, for example through shift working, has on health. -->

<!-- Currently, I am funded by [Wellcome Trust](https://wellcome.ac.uk/){target="_blank"} and [Medical Research Council](https://www.mrc.ac.uk/){target="_blank"} grants. -->

I am a Research Fellow at the [University of Manchester](https://www.manchester.ac.uk/){target="_blank"}, funded by the [North West Lung Centre Charity](https://meu.org.uk/the-north-west-lung-centre-charity/){target="_blank"}.

My research focuses on the relationships between the circadian clock and disease, in particular looking at the effect of disruption to the circadian system, for example through shift working, has on health.

My work is in collaboration with [Dr. Hannah Durrington's](https://www.research.manchester.ac.uk/portal/hannah.durrington.html){target="_blank"} research group and I am part of the [Bioinference](https://manchesterbioinference.github.io/bioinference_website/){target="_blank"} computational research group at Manchester.

I co-lead the Research IT Computation and Data in Research (CaDiR) [UoM UK Biobank Users community](https://bit.ly/cadirUKB){target="_blank"}. I'm a research scholar with [Our Future Health](https://research.ourfuturehealth.org.uk){target="_blank"}.

### Academic history

-   Research Fellow at the University of Manchester <br> *November 2022 - present*

-   Research Associate at OCDEM, University of Oxford <br> *September 2018 - November 2022*

-   Research Associate at the University of Manchester <br> *July 2016 - September 2018*

### Education

-   PhD Statistics and Operational Research (STOR-i): Lancaster University<br> *"Efficient Analysis of Complex Changepoint Problems" Supervised by Prof. Paul Fearnhead and Prof. Adam Letchford.*

-   MRes Statistics and Operational Research (STOR-i) (Distinction): Lancaster University

-   BSc Mathematics (First Class Honours): Lancaster University

### Selected Publications

[Full publication list \>\>](/Publications.html)

-   [**Increased risk of asthma in female night shift workers**](https://doi.org/10.1183/23120541.00137-2025){target="_blank"} *Robert J. Maidstone*, David W. Ray, Junxi Liu, Jack Bowden, Martin K. Rutter and Hannah J. Durrington - ERJ Open Research, 2025.

-   [**Shift work and evening chronotype are related to prevalent non-alcoholic fatty liver disease in 282,303 UK biobank participants**](https://doi.org/10.1530/EC-23-0472){target="_blank"} *Robert Maidstone*, Martin K. Rutter, Thomas Marjot, David W. Ray and Matthew Baxter - Endocrine Connections 13(2), 2024.

-   [**Influence of Artificial Light at Night on Asthma and Allergic Diseases: A Systematic Review and Meta-Analysis**](https://doi.org/10.1186/s12916-024-03291-5){target="_blank"} Andy Deprato, *Robert Maidstone*, Anna Palomar Cros, Ana Adan, Prasun Haldar, Barbara N. Harding, Paige Lacy, Lyle Melenka, Saibal Moitra, Jose Francisco Navarro, Manolis Kogevinas, Hannah J. Durrington and Subhabrata Moitra - BMC Medicine 22(67), 2024.

-   [**Night Shift Work is Associated with an Increased Risk of Asthma**](http://dx.doi.org/10.1136/thoraxjnl-2020-215218){target="_blank"} *Robert J. Maidstone*, James Turner, Celine Vetter, Hassan S. Dashti, Richa Saxena, Frank A.J.L. Sheer, Steven A. Shea, Simon D. Kyle, Deborah A. Lawlor, Andrew S.I. Loudon, John F. Blaikley, Martin K. Rutter, David W. Ray and Hannah J. Durrington - Thorax 76(1), 2021.
