---
title: "Publications"
---

### 2025

-   [**Increased risk of asthma in female night shift workers**](https://doi.org/10.1183/23120541.00137-2025){target="_blank"} *Robert J. Maidstone*, David W. Ray, Junxi Liu, Jack Bowden, Martin K. Rutter and Hannah J. Durrington - ERJ Open Research, 2025.

-   [**Circadian variability in breath volatiles is affected by the timing of inhaled corticosteroids in asthma**](https://doi.org/10.1136/thorax-2024-222073){target="_blank"} Ran Wang, *Robert Maidstone*, Waqar Ahmed, Dave Singh, David Ray, Andrew Loudon, Angela Simpson, Stephen Fowler and Hannah Durrington. ERJ Open Research, 2025.

-   [**Associations between Artificial Light at Night and Mental Health: A Systematic Review and Meta-Analysis.**](https://doi.org/10.1016/j.scitotenv.2025.179188){target="_blank"} Andy Deprato, Prasun Haldar, Jose Francisco Navarro, Barbara N. Harding, Paige Lacy, *Robert Maidstone*, Saibal Moitra, Anna Palomar Cros, Hannah J. Durrington, Manolis Kogevinas, Subhabrata Moitra and Ana Adan. Science of the Total Environment 974, 2025.

-   [**The impact of dosage timing for inhaled corticosteroids in asthma: a randomised three-way crossover trial.**](https://doi.org/10.1136/thorax-2024-222073){target="_blank"} Ran Wang, *Robert Maidstone*, Dave Singh, David Ray, Andrew Loudon, Angela Simpson, and Hannah J. Durrington. Thorax, 2025.

### 2024

-   [**Indoor and outdoor artificial light-at-night (ALAN) and cancer risk: A systematic review and meta-analysis of multiple cancer sites and with a critical appraisal of exposure assessment**](https://doi.org/10.1016/j.scitotenv.2024.177059){target="_blank"} Anna Palomar-Cros, Andy Deprato, Kyriaki Papantoniou, Kurt Straif, Paige Lacy, *Robert Maidstone*, Ana Adan, Prasun Haldar, Saibal Moitra, Jose Francisco Navarro, Hannah Durrington, Subhabrata Moitra and Barbara N. Harding - Science of the Total Environment, 2024.

-   [**The impact of time of day on the diagnostic performance of tests for asthma**](https://doi.org/10.1183/23120541.00916-2023){target="_blank"} Ran Wang, Stephen J. Fowler, *Robert Maidstone*, Laura Healy, Sarah Drake, Lesley Lowe, Angela Simpson, Clare S. Murray and Hannah J. Durrington - ERJ Open Research 10(4), 2024.

-   [**Influence of artificial light at night on asthma and allergic diseases: A systematic review and meta-analysis**](https://doi.org/10.1186/s12916-024-03291-5){target="_blank"} Andy Deprato, *Robert Maidstone*, Anna Palomar Cros, Ana Adan, Prasun Haldar, Barbara N. Harding, Paige Lacy, Lyle Melenka, Saibal Moitra, Jose Francisco Navarro, Manolis Kogevinas, Hannah J. Durrington and Subhabrata Moitra - BMC Medicine 22(67), 2024.

-   [**Shift work and evening chronotype are related to prevalent non-alcoholic fatty liver disease in 282,303 UK biobank participants**](https://doi.org/10.1530/EC-23-0472){target="_blank"} *Robert Maidstone*, Martin K. Rutter, Thomas Marjot, David W. Ray and Matthew Baxter - Endocrine Connections 13(2), 2024.

-   [**Chronotype, but not night shift work, is associated with psoriasis: A cross-sectional study among UK Biobank participants.**](https://doi.org/10.1016/j.jid.2023.07.019){target="_blank"} *Robert Maidstone*, Mudassar Iqbal, Martin K. Rutter, David W. Ray and Helen S. Young - Journal of Investigative Dermatology 144(2), 2024.

### 2023

-   [**The associations of chronotype and shift work with rheumatoid arthritis**](https://doi.org/10.1177/07487304231179595){target="_blank"} Thomas Butler, *Robert Maidstone*, Martin K. Rutter, John McLaughlin, David W. Ray and Julie Gibbs - Journal of Biological Rhythms 38(5), 2023.

-   [**Identification of diurnal rhythmic blood markers in bronchial asthma**](https://doi.org/10.1183/23120541.00161-2023){target="_blank"} Karolina Krakowiak, *Robert J. Maidstone*, Amlan Chakaraborty, Alexandra C. Kendall, Anna Nicolaou, Polly Downton, Andreea-Daniela Cristian, Dave Singh, Andrew S.I. Loudon, David W. Ray and Hannah J. Durrington - ERJ Open Research 9(4), 2023.

-   [**Consequences of collagen induced inflammatory arthritis on circadian regulation of the gut microbiome**](https://doi.org/10.1096/fj.202201728R){target="_blank"} Devin A. Simpkins, Polly Downton, Kathryn J. Gray, Suzanna H. Dickson, *Robert J. Maidstone*, Joanne E. Konkel, Matthew R. Hepworth, David W. Ray, David A. Bechtold and Julie E. Gibbs - The FASEB Journal 37(1), 2023.

### 2022

-   [**The Influence of Artificial Light at Night on Asthma and Allergy, Mental Health, and Cancer Outcomes: A Systematic Scoping Review Protocol**](https://doi.org/10.3390/ijerph19148522){target="_blank"} Andy Deprato, Himasha Rao, Hannah Durrington, *Robert Maidstone*, Ana Adan, Jose Francisco Navarro, Anna Palomar-Cros, Barbara N Harding, Prasun Haldar, Saibal Moitra, Tanusree Moitra, Lyle Melenka, Manolis Kogevinas, Paige Lacy and Subhabrata Moitra - International Journal of Environmental Research and Public Health 19(14), 2022.

-   [**Circadian Clock Function Does Not Require the Histone Methyltransferase MLL3**](https://doi.org/10.1096/fj.202200368R){target="_blank"} Matthew Baxter, Toryn Poolman, Peter Cunningham, Louise Hunter, Maria Voronkov, Gareth B. Kitchen, Laurence Goosey, Nicola Begley, Danielle Kay, Abby Hespe, *Robert Maidstone*, Andrew S.I. Loudon and David W. Ray - The FASEB Journal 36(7), 2022.

-   [**Chronic Inflammatory Arthritis Drives Systemic Changes in Circadian Energy Metabolism**](https://doi.org/10.1073/pnas.2112781119){target="_blank"} Polly Downton, Fabio Sanna, *Robert Maidstone*, Toryn M. Poolman, Edward A. Hayter, Suzanna H. Dickson, Nick A. Ciccone, James O. Early, Antony Adamson, David G. Spiller, Devin A. Simpkins, Matthew Baxter, Roman Fischer, Magnus Rattray, Andrew S.I. Loudon, Julie E. Gibbs, David A. Bechtold and David W. Ray - PNAS 119(18), 2022.

### 2021

-   [**Shift Work is Associated with Positive COVID-19 Status in Hospitalised Patients**](http://dx.doi.org/10.1136/thoraxjnl-2020-216651){target="_blank"} *Robert Maidstone*, Simon G. Anderson, David W. Ray, Martin K. Rutter, Hannah J. Durrington and John F. Blaikley - Thorax 76(6), 2021.

-   [**Circadian Control of Hepatitis B Virus Replication**](https://doi.org/10.1038/s41467-021-21821-0){target="_blank"} Xiaodong Zhuang, Donall Forde, Senko Tsukuda, Valentina D’Arienzo, Laurent Mailly, James M Harris, Peter AC Wing, Helene Borrmann, Mirjam Schilling, Andrea Magri, Claudia Orbegozo Rubio, *Robert J Maidstone*, Mudassar Iqbal, Miguel Garzon, Rosalba Minisini, Mario Pirisi, Sam Butterworth, Peter Balfe, David W Ray, Koichi Watashi, Thomas F Baumert and Jane A McKeating - Nature Communications. 12(1), 2021.

-   [**Night Shift Work is Associated with an Increased Risk of Asthma**](http://dx.doi.org/10.1136/thoraxjnl-2020-215218){target="_blank"} *Robert J. Maidstone*, James Turner, Celine Vetter, Hassan S. Dashti, Richa Saxena, Frank A.J.L. Sheer, Steven A. Shea, Simon D. Kyle, Deborah A. Lawlor, Andrew S.I. Loudon, John F. Blaikley, Martin K. Rutter, David W. Ray and Hannah J. Durrington - Thorax 76(1), 2021.

### 2020

-   [**The clock gene Bmal1 inhibits macrophage motility, phagocytosis, and impairs defense against pneumonia**](https://doi.org/10.1073/pnas.1915932117){target="_blank"} Gareth B Kitchen, Peter S Cunningham, Toryn M Poolman, Mudassar Iqbal, *Robert Maidstone*, Matthew Baxter, James Bagnall, Nicola Begley, Ben Saer, Tracy Hussell, Laura C Matthews, David H Dockrell, Hannah J Durrington, Julie E Gibbs, John F Blaikley, Andrew S Loudon and David W Ray - PNAS 117(3), 2020.

-   [**Cardiac mitochondrial function depends on BUD23 mediated ribosome programming**](https://doi.org/10.7554/eLife.50705){target="_blank"} Matthew Baxter, Maria Voronkov, Toryn Poolman, Gina Galli, Christian Pinali, Laurence Goosey, Abigail Knight, Karolina Krakowiak, *Robert Maidstone*, Mudassar Iqbal, Min Zi, Sukhpal Prehar, Elizabeth J Cartwright, Julie Gibbs, Laura C Matthews, Antony D Adamson, Neil E Humphreys, Pedro Rebelo-Guiomar, Michal Minczuk, David A Bechtold, Andrew Loudon and David Ray - Elife 9, 2020.

-   [**Circadian Asthma Airway Responses are Gated by REV-ERBα**](https://doi.org/10.1183/13993003.02407-2019){target="_blank"} Hannah J. Durrington, Karolina Krakowiak, Peter Meijer, Nicola Begley, *Robert Maidstone*, Laurence Goosey, Julie E. Gibbs, John F. Blaikley, Lisa G. Gregory, Clare M. Lloyd, Andrew S. I. Loudon and David W. Ray - European Respiratory Journal 56(6), 2020.

-   [**Circadian Rhythmicity of Sphingolipids in Allergic Asthma**](https://doi.org/10.1183/13993003.congress-2020.616){target="_blank"} Ran Wang, *Robert Maidstone*, David Ray, Anna Nicolaou, Alexandra Kendall and Hannah Durrington - European Respiratory Journal 56(64), 2020.

### 2019

-   [**Circadian Rhythm of Exhaled Biomarkers in Health and Asthma**](https://doi.org/10.1183/13993003.01068-2019){target="_blank"} Maxim Wilkinson, *Robert Maidstone*, Andrew Loudon, John Blaikley, Iain R White, Dave Singh, David W. Ray, Royston Goodacre, Stephen J. Fowler and Hannah J. Durrington - European Respiratory Journal 54(4), 2019.

-   [**Rheumatoid Arthritis Reprograms Circadian Output Pathways**](https://doi.org/10.1186/s13075-019-1825-y){target="_blank"} Toryn M Poolman, Julie Gibbs, Amy L Walker, Suzanna Dickson, Laura Farrell, James Hensman, Alexandra C Kendall, *Robert Maidstone*, Stacey Warwood, Andrew Loudon, Magnus Rattray, Ian N Bruce, Anna Nicolaou and David W Ray - Arthritis Research and Therapy, 21(47), 2019.

-   [**Monthly variance in UK renal transplantation activity: a national retrospective cohort study**](https://doi.org/10.1136/bmjopen-2018-028786){target="_blank"} Marcus Lowe, Robert Maidstone, Kay Poulton, Judith Worthington, Hannah J Durrington, David W Ray, David van Dellen, Argiris Asderakis, John Blaikley and Titus Augustine - BMJ Open 9(9), 2019.

-   [**Genome-Wide Effect of Pulmonary Airway Epithelial Cell-Specific *Bmal1* Deletion**](https://doi.org/10.1096/fj.201801682R){target="_blank"} Zhenguang Zhang, Louise Hunter, Gang Wu, *Robert Maidstone*, Yasutaka Mizoro, Ryan Vonslow, Mark Fife, Thomas Hopwood, Nicola Begley, Ben Saer, Ping Wang, Peter Cunningham, Matthew Baxter, Hannah Durrington, John F Blaikley, Tracy Hussell, Magnus Rattray, John B Hogenesch, Julie Gibbs, David W Ray and Andrew SI Loudon - The FASEB Journal, 33(5), 6226-6238, 2019.

-   [**Cough Rhythms in Asthma: Potential Implication for Management**](https://doi.org/10.1016/j.jaip.2018.12.020){target="_blank"} Sirat Lodhi, Jaclyn A Smith, Imran Satia, Kimberley J Holt, *Robert J Maidstone* and Hannah J Durrington - Journal of Allergy and Clinical Immunology: In Practice 7(6), 2019.

-   [**Incidence of Primary Graft Dysfunction After Lung Transplantation is Altered by Timing of Allograft Implantation**](/staff/robert.maidstone/publication/cunningham2018/index.html){target="_blank"} Peter S Cunningham, *Robert Maidstone*, Hannah J Durrington, Rajamayier V Venkateswaran, Marcelo Cypel, Shaf Keshavjee, Julie E Gibbs, Andrew S Loudon, Chung-Wai Chow, David W Ray and John F Blaikley - Thorax 74(4), 2019.

-   [**Detecting Changes in Slope with an** $L_0$ Penalty](https://doi.org/10.1080/10618600.2018.1512868){target="_blank"} Paul Fearnhead, *Robert Maidstone* and Adam Letchford - Journal of Computational and Graphical Statistics 28(2), 2019.

### 2018

-   [**Time of Day Affects Eosinophil Biomarkers in Asthma: Implications for Diagnosis and Treatment**](https://doi.org/10.1164/rccm.201807-1289LE){target="_blank"} Hannah J. Durrington, Gael O. Gioan-Tavernier, *Robert J. Maidstone*, Karolina Krakowiak, Andrew S.I. Loudon, John F. Blaikley, Stephen J. Fowler, Dave Singh, Angela Simpson and David W. Ray - American Journal of Respiratory and Critical Care Medicine 198(12), 1578-1581, 2018.

-   [**REV-ERBa Couples the Circadian Clock to Hepatic Glucocorticoid Action**](https://doi.org/10.1172/JCI96138){target="_blank"} Giorgio Caratti, Mudassar Iqbal, Louise Hunter, Donghwan Kim, Ping Wang, Ryan M. Vonslow, Nicola Begley, Abigail J. Tetley, Joanna L. Woodburn, Marie Pariollaud, *Robert Maidstone*, Ian J. Donaldson, Zhenguang Zhang, Louise M. Ince, Gareth Kitchen, Matthew Baxter, Toryn M. Poolman, Dion A. Daniels, David R. Stirling, Chad Brocker, Frank Gonzalez, Andrew S.I. Loudon, David A. Bechtold, Magnus Rattray, Laura C. Matthews and David W. Ray - Journal of Clinical Investigation 128(10), 4454-4471, 2018.

### \< 2018

-   [**On Optimal Multiple Changepoint Algorithms for Large Data**](https://doi.org/10.1007/s11222-016-9636-3){target="_blank"} *Robert Maidstone*, Toby Hocking, Guillem Rigaill and Paul Fearnhead - Statistics and Computing 27(2), 519-533, 2017.

-   [**Efficient Analysis of Complex Changepoint Problems**](https://eprints.lancs.ac.uk/id/eprint/83055/1/2016MaidstonePhD.pdf){target="_blank"} *Robert Maidstone* - Thesis submitted for the degree of Doctor of Philosophy at Lancaster University under supervision of Adam Letchford and Paul Fearnhead, 2016.

-   [**Comment on "Multiscale Change-Point Inference" by K. Frick, A. Munk and H. Sieling**](https://personalpages.manchester.ac.uk/staff/robert.maidstone/maidstonepickering2013.pdf){target="_blank"} *Robert Maidstone* and Benjamin Pickering - Discussion piece published in the Journal of the Royal Statistical Society Series B, 2013.
