---
title: "Robert Maidstone"
---

<!-- I am a Research Associate at [OCDEM](https://www.rdm.ox.ac.uk/about/our-divisions/oxford-centre-for-diabetes-endocrinology-and-metabolism){target="_blank"} (University of Oxford), part of [Prof. David Ray's](https://www.rdm.ox.ac.uk/people/david-ray){target="_blank"} lab. -->

<!-- My recent work uses computational techniques to explore the relationships between the circadian clock and disease. In particular looking at the effect of disruption to the circadian system, for example through shift working, has on health. -->

<!-- Currently, I am funded by [Wellcome Trust](https://wellcome.ac.uk/){target="_blank"} and [Medical Research Council](https://www.mrc.ac.uk/){target="_blank"} grants. -->

I am a Research Fellow at the [University of Manchester](https://www.manchester.ac.uk/){target="_blank"}, part of [Dr. Hannah Durrington's](https://www.research.manchester.ac.uk/portal/hannah.durrington.html){target="_blank"} research group.

My recent work uses computational techniques to explore the relationships between the circadian clock and disease. In particular looking at the effect of disruption to the circadian system, for example through shift working, has on health.

Currently, I am funded by [Asthma & Lung UK](https://www.asthma.org.uk/){target="_blank"}.

### Academic history

-   Research Fellow at the University of Manchester <br>
*November 2022 - present; with Dr. Hannah Durrington*

-   Research Associate at OCDEM, University of Oxford <br> *September 2018 - November 2022; with Prof. David Ray*

-   Research Associate at the University of Manchester <br> *July 2016 - September 2018; with Prof. David Ray and Prof. Andrew Loudon*

### Education

-   PhD Statistics and Operational Research (STOR-i): Lancaster University<br> *"Efficient Analysis of Complex Changepoint Problems" Supervised by Prof. Paul Fearnhead and Prof. Adam Letchford.*

-   MRes Statistics and Operational Research (STOR-i) (Distinction): Lancaster University

-   BSc Mathematics (First Class Honours): Lancaster University

### Selected Publications

[Full publication list \>\>](/Publications.html)

-   [**Chronic Inflammatory Arthritis Drives Systemic Changes in Circadian Energy Metabolism**](https://doi.org/10.1073/pnas.2112781119){target="_blank"} Polly Downton, Fabio Sanna, *Robert Maidstone*, Toryn M. Poolman, Edward A. Hayter, Suzanna H. Dickson, Nick A. Ciccone, James O. Early, Antony Adamson, David G. Spiller, Devin A. Simpkins, Matthew Baxter, Roman Fischer, Magnus Rattray, Andrew S.I. Loudon, Julie E. Gibbs, David A. Bechtold and David W. Ray - PNAS 119(18), 2022.

-   [**Shift Work is Associated with Positive COVID-19 Status in Hospitalised Patients**](http://dx.doi.org/10.1136/thoraxjnl-2020-216651){target="_blank"} *Robert Maidstone*, Simon G. Anderson, David W. Ray, Martin K. Rutter, Hannah J. Durrington and John F. Blaikley - Thorax 76(6), 2021.

-   [**Night Shift Work is Associated with an Increased Risk of Asthma**](http://dx.doi.org/10.1136/thoraxjnl-2020-215218){target="_blank"} *Robert J. Maidstone*, James Turner, Celine Vetter, Hassan S. Dashti, Richa Saxena, Frank A.J.L. Sheer, Steven A. Shea, Simon D. Kyle, Deborah A. Lawlor, Andrew S.I. Loudon, John F. Blaikley, Martin K. Rutter, David W. Ray and Hannah J. Durrington - Thorax 76(1), 2021.

-   [**On Optimal Multiple Changepoint Algorithms for Large Data**](https://doi.org/10.1007/s11222-016-9636-3){target="_blank"} *Robert Maidstone*, Toby Hocking, Guillem Rigaill and Paul Fearnhead - Statistics and Computing 27(2), 519-533, 2017.
